
required= [
  "github.com/golang/lint/golint",
  "github.com/pressly/goose",
  ## required for goose
  "github.com/lib/pq",
  "github.com/mattn/go-sqlite3",
  "github.com/ziutek/mymysql/godrv"
  ## end required for goose
]

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/golang/lint"

[[constraint]]
  name = "github.com/pressly/goose"
  version = "^2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "^1.4.0"

[[constraint]]
  name = "github.com/ziutek/mymysql"
  version = "^1.5.4"
