
required= [
  "github.com/golang/lint/golint"
]

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/golang/lint"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/objx"
